services:
  database:
    container_name: database
    image: mysql:8.0.38
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: ChangeMe
      MYSQL_TCP_PORT: 3307
    volumes:
      - /var/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.3.9
        XDEBUG_VERSION: 3.3.2
        XDEBUG_CONFIG: "client_port=9009 client_host=localhost log=/tmp/xdebug_remote.log"
        XDEBUG_MODE: "debug,develop,coverage"
    volumes:
      - ..:/app
      - ${HOME}/.ssh/:/root/.ssh/:ro
